services:
  api:
    container_name: api
    build: .
    command: /bin/bash init.sh
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
