services:
  api:
    container_name: api
    build: .
    command: /bin/bash -c "chmod +x scripts/*.sh && ./scripts/init.sh && ./scripts/start.sh"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
