services:
  api:
    container_name: api
    build: .
    command: sh -c ./init.sh
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
