services:
  api:
    container_name: api
    build: .
    command: >
        sh -c " \
        python -m prisma generate &&  \
        python -m prisma db push && \
        python -m seeds.main &&  \
        uvicorn api.main:app --host ${API_HOST} --port ${API_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
  