services:
  api:
    container_name: api
    build: .
    command: >
        sh -c " \
        python -m prisma generate &&  \
        python -m prisma db push --force-reset && \
        python -m seeds.main && \
        uvicorn api.main:app --host ${API_HOST} --port ${API_PORT}"
    volumes:
      - .:/app
    # environment:
    #   - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_INNER_PORT}/${POSTGRES_DB}"
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
      
  # db:
  #   container_name: db
  #   image: postgres:13
  #   env_file:
  #     - .env
  #   ports:
  #     - "${DB_PORT}:${DB_INNER_PORT}"
