name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> .env
        echo "API_HOST=${{ env.API_HOST }}" >> .env
        echo "API_PORT=${{ env.API_PORT }}" >> .env
        echo "POSTGRES_USER=${{ env.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ env.POSTGRES_DB }}" >> .env

    - name: Start docker compose
      run: |
          ls
          docker compose up -d --build

    - name: Check docker compose status
      run: |
        docker-compose ps
        docker-compose logs --tail=50
          