name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: server
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set env variables
      run: |
        echo "API_HOST=${{ vars.API_HOST }}" >> .env
        echo "API_PORT=${{ vars.API_PORT }}" >> .env
        echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> .env 
        echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env 
        echo "DATABASE_URL=postgresql://${{vars.POSTGRES_USER}}:${{vars.POSTGRES_PASSWORD}}@${{vars.POSTGRES_HOST}}:5432/${{vars.POSTGRES_DB}}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{vars.AWS_ACCESS_KEY_ID}}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{vars.AWS_SECRET_ACCESS_KEY}}" >> .env
        echo "AWS_ENDPOINT_URL=${{vars.AWS_ENDPOINT_URL}}" >> .env
        echo "AWS_BUCKET_NAME=${{vars.AWS_BUCKET_NAME}}" >> .env
        echo "JWT_ACCESS_SECRET=${{vars.JWT_ACCESS_SECRET}}" >> .env
        echo "JWT_REFRESH_SECRET=${{vars.JWT_REFRESH_SECRET}}" >> .env
        echo "JWT_ACCESS_EXPIRE_DAYS=${{vars.JWT_ACCESS_EXPIRE_DAYS}}" >> .env
        echo "JWT_REFRESH_EXPIRE_DAYS=${{vars.JWT_REFRESH_EXPIRE_DAYS}}" >> .env
        echo "S3_SEEDS_DATA_PATH=${{vars.S3_SEEDS_DATA_PATH}}" >> .env

    - name: Start docker compose
      run: |
          docker compose up -d --build
          